// Generated by tooling/mockups/scrublings/gen-sprites.mjs from the mockup grids. Do not edit by hand.
import type { SpriteSheet } from '../spriteTypes';

const sheet: SpriteSheet = {
  id: 'spider',
  palette: {"K":"#070a0f","D":"#2a1236","d":"#4a2160","O":"#ff8c2a","o":"#ffc27a","S":"#e9e4f0","M":"#c7d3de","Z":"#c88bff"},
  frames: {
    idle1: ["","","","","","","","","","","","","","","",".......KKKKKK","......KDDDDDDK","......KDOODOOK","......KDDDDDDK","....KKKDdDDdDKKK","...K.KDDDDDDDDK.K","..K..KDdDDDDdDK..K","..K..KKDDDDDDKK..K",".K..K..KKKKKK..K..K",".K..K..........K..K","KK.KK..........KK.KK","",""],
    idle2: ["","","","","","","","","","","","","","","",".......KKKKKK","......KDDDDDDK","......KDDDDDDK","......KDDDDDDK","....KKKDdDDdDKKK","...K.KDDDDDDDDK.K","..K..KDdDDDDdDK..K","..K..KKDDDDDDKK..K",".K..K..KKKKKK..K..K",".K..K..........K..K","KK.KK..........KK.KK","",""],
    idle3: ["","","","","","","","","","","","","","","",".......KKKKKK","......KDDDDDDK","......KDOODOOK","......KDDDDDDK","....KKKDdDDdDKKK","...K.KDDDDDDDDK.K","..K..KDdDDDDdDK..K","..K..KKDDDDDDKK..K",".K..K..KKKKKK..K..K",".K..K..........K..K",".K.KK..........KK.K","",""],
    look: ["","","","","","","","","","","","","","","",".......KKKKKK","......KDDDDDDK","......KDDOODOOK","......KDDDDDDK","....KKKDdDDdDKKK","...K.KDDDDDDDDK.K","..K..KDdDDDDdDK..K","..K..KKDDDDDDKK..K",".K..K..KKKKKK..K..K",".K..K..........K..K","KK.KK..........KK.KK","",""],
    walk1: ["","","","","","","","","","","","","","","",".......KKKKKK","......KDDDDDDK","......KDOODOOK","......KDDDDDDK","....KKKDdDDdDKKK","...K.KDDDDDDDDK.K","..K..KDdDDDDdDK..K","..K..KKDDDDDDKK..K",".K..K..KKKKKK..K..K",".K..K..........K..K",".K.KK..........KK.K","",""],
    walk2: ["","","","","","","","","","","","","","","",".......KKKKKK","......KDDDDDDK","......KDOODOOK","......KDDDDDDK","....KKKDdDDdDKKK","...K.KDDDDDDDDK.K","..K..KDdDDDDdDK..K","..K..KKDDDDDDKK..K","..K.K..KKKKKK..K.K","..K.K..........K.K",".KK.K..........K.KK","",""],
    dangle1: [".........S",".........S",".........S",".........S",".........S",".........S",".........S",".........S",".........S",".......KKKKKK","......KDDDDDDK","......KDOODOOK","......KDDDDDDK",".....KKKDdDDdDKKK","....K.KDDDDDDDDK.K","....K.KDdDDDDdDK.K","....KKKKDDDDDDKKKK",".......KKKKKK","","","","","","","","","",""],
    dangle2: [".........S",".........S",".........S",".........S",".........S",".........S",".........S",".......KKKKKK","......KDDDDDDK","......KDOODOOK","......KDDDDDDK",".....KKKDdDDdDKKK","....K.KDDDDDDDDK.K","....K.KDdDDDDdDK.K","....KKKKDDDDDDKKKK",".......KKKKKK","","","","","","","","","","","",""],
    hang1: ["","","","","","","","","","",".........S",".........S",".........S",".......KKKKKK","..K..KKDDDDDDKK..K","..K..KDdDDDDdDK..K","...K.KDDDDDDDDK.K","....KKKDdDDdDKKK","......KDDDDDDK","......KDOODOOK","......KDDDDDDK",".......KKKKKK","","","","","",""],
    hang2: ["","","","","","","","","","","",".........S",".........S",".........S",".......KKKKKK","..K..KKDDDDDDKK..K","..K..KDdDDDDdDK..K","...K.KDDDDDDDDK.K","....KKKDdDDdDKKK","......KDDDDDDK","......KDOODOOK","......KDDDDDDK",".......KKKKKK","","","","",""],
    wrap1: ["","","","","","","","","","","","","","","",".......KKKKKK","......KDDDDDDK","......KDOODOOK","......KDDDDDDK","....KKKDdDDdDKKK","...K.KDDDDDDDDK.K.MM","..K..KDdDDDDdDK..KMM","..K..KKDDDDDDKK..KSS",".K..K..KKKKKK..K..K",".K..K..........K..K","KK.KK..........KK.KK","",""],
    wrap2: ["","","","","","","","","","","","","","","",".......KKKKKK","......KDDDDDDK","......KDOODOOK","......KDDDDDDK","....KKKDdDDdDKKK..SS","...K.KDDDDDDDDK.K.SM","..K..KDdDDDDdDK..KMS","..K..KKDDDDDDKK..KSS",".K..K..KKKKKK..K..K",".K..K..........K..K","KK.KK..........KK.KK","",""],
    spin1: ["","","","","","","","","","","","","","","",".......KKKKKK","S.....KDDDDDDK","......KDOODOOK",".S....KDDDDDDK","....KKKDdDDdDKKK","S..K.KDDDDDDDDK.K","..K..KDdDDDDdDK..K",".SK..KKDDDDDDKK..K",".K..K..KKKKKK..K..K",".K..K..........K..K","KK.KK..........KK.KK","",""],
    spin2: ["","","","","","","","","","","","","","","","S......KKKKKK","......KDDDDDDK",".S....KDOODOOK","......KDDDDDDK","S...KKKDdDDdDKKK","...K.KDDDDDDDDK.K",".SK..KDdDDDDdDK..K","..K..KKDDDDDDKK..K",".K..K..KKKKKK..K..K",".K..K..........K..K","KK.KK..........KK.KK","",""],
    tangled1: ["","","","","","","","","","","","","","","","","K..K..........K..K",".K..K........K..K","..K..KKKKKKKKK..K","..K..KDDDDDDDDK.K","...KKKDdDDDDdDKKK",".....KDDDDDDDDK",".....KKDDDDDDKK","......KDOODOOK","......KDDDDDDK",".......KKKKKK","",""],
    tangled2: ["","","","","","","","","","","","","","","","",".K..K........K..K","K..K..........K..K","..K..KKKKKKKKK..K","..K..KDDDDDDDDK.K","...KKKDdDDDDdDKKK",".....KDDDDDDDDK",".....KKDDDDDDKK","......KDOODOOK","......KDDDDDDK",".......KKKKKK","",""],
    sleep: ["","","","","","","","","","","","","","",".................Z",".......KKKKKK...Z","......KDDDDDDK","......KDDDDDDK","......KDDDDDDK","....KKKDdDDdDKKK","...K.KDDDDDDDDK.K","..K..KDdDDDDdDK..K","..K..KKDDDDDDKK..K",".K..K.SKKKKKKS.K..K",".K..K.S.S..S.S.K..K","KK.KK..........KK.KK","",""],
    boo1: ["","","","","","","","","","","","","","","",".......KKKKKK","......KDDDDDDK","......KOOODOOOK","......KDDDDDDK","..KKKKKDdDDdDKKKKK",".K...KDDDDDDDDK...K","K....KDdDDDDdDK....K","K....KKDDDDDDKK....K","K...K..KKKKKK..K...K","K...K..........K...K","K...K..........K...K","",""],
    boo2: ["","","","","","","","","","","","","","",".......KKKKKK","......KDDDDDDK","......KOOODOOOK","......KDDDDDDK","..KKKKKDdDDdDKKKKK",".K...KDDDDDDDDK...K","K....KDdDDDDdDK....K","K....KKDDDDDDKK....K","K...K..KKKKKK..K...K","K...K..........K...K","K...K..........K...K","","",""],
  },
  activities: {"idle":["idle1","idle1","idle2","idle1","idle3"],"walk":["walk1","walk2"],"look":["look"],"dangle":["dangle1","dangle2"],"hang":["hang1","hang2"],"wrap":["wrap1","wrap2"],"spin":["spin1","spin2"],"tangled":["tangled1","tangled2"],"sleep":["sleep"],"boo":["boo1","boo2"]},
};

export default sheet;
